
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]

##VGA Connector

set_property PACKAGE_PIN G19 [get_ports {VGA_R[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN H19 [get_ports {VGA_R[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN J19 [get_ports {VGA_R[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN N19 [get_ports {VGA_R[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN N18 [get_ports {VGA_G[0]}]  
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN L18 [get_ports {VGA_G[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN K18 [get_ports {VGA_G[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN J18 [get_ports {VGA_G[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN J17 [get_ports {VGA_B[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN H17 [get_ports {VGA_B[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN G17 [get_ports {VGA_B[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN D17 [get_ports {VGA_B[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN P19 [get_ports VGA_HS]
    set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property PACKAGE_PIN R19 [get_ports VGA_VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
    
       
    
    
    set_property PACKAGE_PIN U18 [get_ports {button}]
set_property IOSTANDARD LVCMOS33 [get_ports {button}]
set_property PACKAGE_PIN T17 [get_ports {RST}]
set_property IOSTANDARD LVCMOS33 [get_ports {RST}]
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property PACKAGE_PIN W7 [get_ports {cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[7]}]
set_property PACKAGE_PIN W6 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property PACKAGE_PIN U8 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property PACKAGE_PIN V8 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property PACKAGE_PIN U5 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property PACKAGE_PIN V5 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property PACKAGE_PIN U7 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property PACKAGE_PIN V7 [get_ports {cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]

set_property PACKAGE_PIN V2 [get_ports {min0_in[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min0_in[0]}]
set_property PACKAGE_PIN T3 [get_ports {min0_in[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min0_in[1]}]
set_property PACKAGE_PIN T2 [get_ports {min0_in[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min0_in[2]}]
set_property PACKAGE_PIN R3 [get_ports {min0_in[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min0_in[3]}]
set_property PACKAGE_PIN W2 [get_ports {min1_in[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min1_in[0]}]
set_property PACKAGE_PIN U1 [get_ports {min1_in[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min1_in[1]}]
set_property PACKAGE_PIN T1 [get_ports {min1_in[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min1_in[2]}]
set_property PACKAGE_PIN R2 [get_ports {min1_in[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {min1_in[3]}]

set_property PACKAGE_PIN B15 [get_ports {buzzer}] 
   set_property IOSTANDARD LVCMOS33 [get_ports {buzzer}]

##led
 #set_property PACKAGE_PIN U16 [get_ports {buzzer}]
 #set_property IOSTANDARD LVCMOS33 [get_ports {buzzer}]
 

 set_property PACKAGE_PIN V17 [get_ports {counter}]
 set_property IOSTANDARD LVCMOS33 [get_ports {counter}]
 
 
set_property PACKAGE_PIN W19 [get_ports {back}]
set_property IOSTANDARD LVCMOS33 [get_ports {back}]

set_property PACKAGE_PIN T18 [get_ports {up}]
set_property IOSTANDARD LVCMOS33 [get_ports {up}]

set_property PACKAGE_PIN U17 [get_ports {down}]
set_property IOSTANDARD LVCMOS33 [get_ports {down}]